### ISSUE TITLE
转换文件出错，HNParsePage.py有问题

### ISSUE THREAD

**Issue by maz-1** [caj2pdf/caj2pdf#58]
[混凝土道面评价指标分析_谢永亮.zip](https://github.com/caj2pdf/caj2pdf/files/5866808/_.zip)

Traceback (most recent call last):
  File "caj2pdf", line 47, in <module>
    caj.convert(args.output)
  File "G:\ling-pc\D7200\TOOLS\caj2pdf\cajparser.py", line 101, in convert
    self._convert_hn(dest)
  File "G:\ling-pc\D7200\TOOLS\caj2pdf\cajparser.py", line 308, in _convert_hn
    page_data = HNParsePage(output, page_style)
  File "G:\ling-pc\D7200\TOOLS\caj2pdf\HNParsePage.py", line 72, in __init__
    (dispatch_code,) = struct.unpack("H", self.data[self.offset:self.offset+2])
struct.error: unpack requires a buffer of 2 bytes

经测试把HNParsePage.py第71行的
while (self.offset < self.data_length):
改成
while (self.offset < self.data_length - 1):
就不报错了，转换也ok

**Comment by cnfree** [comment]
赞！

**Comment by HinTak** [comment]
Thanks for the same and the investigation - I have committed a equivalent fix " ... <= ... -2", rather that "... < ... - 1". I think it looks better, as it is more obvious about 2 being needed. They are functionally the same, of course.
