### ISSUE TITLE
一个无法转换的例子

### ISSUE THREAD

**Issue by frank-cmy** [caj2pdf/caj2pdf#69]
在转换一个caj的时候，出现Image Count 4 != 2。
查了代码，应该是在cajparser.py的第329行：
                 `raise SystemExit("Image Count %d != %d" % (len(page_data.figures), images_per_page)   `
不太理解这里的原因，目标文件放在了附件的zip中。
[12.zip](https://github.com/caj2pdf/caj2pdf/files/7467122/12.zip)

**Comment by HinTak** [comment]
Sample commited to the sample repo. I'll see if I can find some time to have a look.

**Comment by HinTak** [comment]
I fixed the crash so it now finishes - the figures at those pages still look a bit wrong. If you have access to the official conversion I'll like to know, otherwise I'll try it myself and compare at some point.

**Comment by HinTak** [comment]
It probably shouldn't be closed just yet.

**Comment by HinTak** [comment]
Using native readerex to convert, it seems the the extra rectangular regions are clip paths. In most other caj's, the additional images are positional as a whole inside a region. This caj is different in that much larger jpeg images are embedded then scaled and clipped. So besides just the rectangular region on the page the image should go in, there are extra info about how to cut the image and showing only portion of it.

**Comment by K-gihu** [comment]
Same problem for [光波导光学相控阵技术的理论和实验研究_梁华伟.caj](https://github.com/K-gihu/Images/blob/master/%E5%85%89%E6%B3%A2%E5%AF%BC%E5%85%89%E5%AD%A6%E7%9B%B8%E6%8E%A7%E9%98%B5%E6%8A%80%E6%9C%AF%E7%9A%84%E7%90%86%E8%AE%BA%E5%92%8C%E5%AE%9E%E9%AA%8C%E7%A0%94%E7%A9%B6_%E6%A2%81%E5%8D%8E%E4%BC%9F.caj).
caj2pdf convert the file resulted in  
```
Image Count 5 != 2
```
and caj2pdf parse the file resulted in the following Traceback
```
Traceback (most recent call last):
  File "/home/user/.local/bin/caj2pdf", line 68, in <module>
    caj.parse()
  File "/home/user/gitrepos/caj2pdf/cajparser.py", line 125, in parse
    self._parse_hn()
  File "/home/user/gitrepos/caj2pdf/cajparser.py", line 478, in _parse_hn
    page_data = HNParsePage(output, page_style)
  File "/home/user/gitrepos/caj2pdf/HNParsePage.py", line 75, in __init__
    dispatch[dispatch_code](self, dispatch_code)
  File "/home/user/gitrepos/caj2pdf/HNParsePage.py", line 53, in Figure
    (ignore1, offset_x, offset_y, size_x, size_y, int2, int3, int4, int5)= struct.unpack("<HHHHHIIII", self.data[self.offset:self.offset+26])
struct.error: unpack requires a buffer of 26 bytes
```

**Comment by HinTak** [comment]
Just commited update, and 光波导光学相控阵技术的理论和实验研究_梁华伟.caj run to completion now with current head. Still same issues with the other file: some figures should be magnified and clipped, instead of showing in full and shrinked in fit.

**Comment by K-gihu** [comment]
Sorry for not updating to the latest commit and Thanks for your reply!

**Comment by HinTak** [comment]
Seems to work fine with some warnings after fixing #76 now. Seem some caj just have extra garbage at end of pages.
